
---
apiVersion: apps/v1
kind: Deployment
metadata:
 name: deploy-rolling
 labels:
  ENV: Dev
spec:
 replicas: 6
 selector:
  matchLabels:
   ENV: Dev
 strategy:
  type: RollingUpdate
  rollingUpdate:
   maxSurge: 2
   maxUnavailable: 2
 template:
  metadata:
   name: deploy-pod
   labels:
    ENV: Dev
  spec:
   containers:
    - name: deploy-con
      image: nginx:1.16
      ports:
       - containerPort: 80
