

---
apiVersion: apps/v1
kind: Deployment
metadata:
 name: deploy-obj1
 labels:
  app: nginx
  role: dev
  location: India
spec:
 replicas: 3
 minReadySeconds: 10
 strategy:
  type: RollingUpdate
  rollingUpdate:
   maxSurge: 1
   maxUnavailable: 1
 selector:
  matchLabels:
   role: dev
 template:
  metadata:
   name: deploy-pod
   labels:
    role: dev
  spec:
   containers:
    - name: deploy-cont
      image: nginx:1.16
      ports:
       - containerPort: 80
      readinessProbe:
         exec:
           command:
             - "cat"
             - "/tmp/health"
         initialDelaySeconds: 10
         periodSeconds: 5
         timeoutSeconds: 20
         successThreshold: 1
         failureThreshold: 1
      livenessProbe:
         exec:
           command:
             - "cat"
             - "/tmp/health"
         initialDelaySeconds: 30
         periodSeconds: 10
         successThreshold: 1
         failureThreshold: 2
         timeoutSeconds: 40
...

---
apiVersion: v1
kind: Service
metadata:
  name: myservice1
  labels:
   role: dev
spec:
  type: NodePort
  selector:
    role: dev
    #app: myapp
  ports:
  - port: 7000
    targetPort: 80
