
---
apiVersion: apps/v1
kind: Deployment
metadata:
 name: deployobj
 labels:
   app: nginx
   env: test
spec:
 replicas: 3
 selector:
  matchLabels:
   app: nginx
 template:
  metadata:
   labels:
    app: nginx
  spec:
   containers:
    - name: nginxcont
      image: nginx
      ports:
       - containerPort: 80 

