
---
apiVersion: v1
kind: Pod
metadata:
 name: postgres-pod
 labels:
  author: mungaras
  tier: db
spec:
 containers:
  - name: postgress-cont
    image: postgres
    env:
     - name: POSTGRES_PASSWORD
       valueFrom:
        secretKeyRef:
         name: mysecrets
         key: password
     - name: POSTGRES_USER
       valueFrom:
        secretKeyRef:
         name: mysecrets
         key: user
     - name: POSTGRES_DB
       valueFrom:
        secretKeyRef:
         name: mysecrets
         key: db
         
