
apiVersion: v1
kind: Pod
metadata:
  name: sidecar
  labels:
    app: nginx
    owner: sai
spec:
  volumes:
   - name: logs
     emptyDir: {}
  containers:
   - name: nginx-cont
     image: nginx
     ports:
      - containerPort: 80
     volumeMounts: 
      - name: logs
        mountPath: /var/www/html
   - name: busybox-cont
     image: busybox
     command:
      ["/bin/sh"]
     args:
      ["-c", "while true; do date >> /var/log/date.txt; sleep 10;done"]
     volumeMounts:
      - name: logs
        mountPath: /var/log/ 

