
---
apiVersion: v1
kind: Pod
metadata:
  name: testpod1
  namespace: myns
  labels:
    env: test
    app: web
spec:
  containers:
   - name: container2
     image: nginx
     ports:
      - containerPort: 80
        hostPort: 8080
